### PR TITLE
Add TypeScript types

### PR DESCRIPTION
**Pull request by dguo**
Thanks for this library! I'm using it for https://github.com/dguo/chromatastic. I'm switching to TypeScript, and it'd be great if these types could be included with the library.

### CODE REVIEW

**Comment by dguo** [comment]
Sorry, I accidentally deleted the branch, which automatically closed the PR. I undeleted it.

**Review by russoedu — APPROVED** [review]
Thanks for contributing!

**Comment by dguo** [comment]
Hi @russoedu, when you get a chance, it'd be great if you could publish a new version to npm.

**Comment by russoedu** [comment]
Sorry, mate.
I completely forgot to do it (and how to do it).
I just published a new version (v1.1.1) with the typed interface on it.

**Comment by dguo** [comment]
No worries. Thank you very much!

**Pull request merged**
